releases/20201219050137/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "users#index"
  get 'log_in' => 'sessions#new', :as => :log_in
  post 'log_out' => 'sessions#destroy', :as => :log_out
  # get '/log_in' => 'sessions#new', :as => :log_in
  # post '/log_out' => 'sessions#destroy', :as => :log_out

  resources :users
  get '/sign_up', to: 'users#new', as: :sign_up
  resources :sessions, only: [:new, :create, :destroy]
end

releases/20201219050137/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

releases/20201219050137/app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!

  before_create :setup_default_role_for_new_users

  ROLES = %w[guest manager admin]

  validates :password, length: { minimum: 5 }, if: -> { new_record? || changes["password"] }
  validates :password, confirmation: true, if: -> { new_record? || changes["password"] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes["password"] }
  validates :email, uniqueness: true
  validates :prenom, uniqueness: true

	def self.users_alphabet
	 users_alphabet = User.order(prenom: :asc)
	end

private

	def setup_default_role_for_new_users
		if self.role.blank?
		self.role = "guest"
		end
	end
end

releases/20201219050137/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

before_action :require_login

private
  # Overwrite the method sorcery calls when it
    # detects a non-authenticated request.
    def not_authenticated
      # Make sure that we reference the route from the main app.
      redirect_to main_app.log_in_path
    end
end

releases/20201219050137/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    skip_before_action :require_login, except: [:destroy]

  	def new
  	    @user = User.new
  	end

    def create
      if @user = login(params[:email], params[:password])
          redirect_back_or_to(root_path, notice: 'Connexion réussie !')
      else
       flash.now[:error] = "Oups! une erreur semble-t-il... veuillez recommencez s'il vous plaît."
       render action: 'new'
      end
  end

    def destroy
      logout
      redirect_back_or_to(root_path, notice: 'Déconnecté !')
    end
end

releases/20201219050137/app/controllers/users_controller.rb
class UsersController < ApplicationController

  skip_before_action :require_login, only: [:index, :new, :create]
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all

  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    if @user.save
      login(params[:user][:email], params[:user][:password])
      redirect_to root_path, notice: 'Bienvenue !'
    else
      render 'new'
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'L\'utilisateur a bien été modifié.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'L\'utilisateur a bien été supprimé.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation, :nom, :prenom, :telephone, :role)
    end
end

releases/20201219050137/app/helpers/application_helper.rb
module ApplicationHelper
end

releases/20201219050137/app/views/layouts/_connexion.html.erb
<div class="container">
  <nav class="nav navbar-light bg-inverse navbar-nav navbar-left connexion">
    <div class="nav navbar-nav navbar-right connexion">
      <% if current_user %>
      <br>
        <h4>Bienvenue ! <span class="label label-info"><%= current_user.prenom%></span></h4>
          <%= link_to "Se déconnecter", :log_out, method: :post, :class => 'btn btn-lg btn-success' %>
       <% end %>
    </div>
  </nav>
  <div class="logo">
  <%= link_to "https://ecranvillage.net", :target => "_blank", :rel => "noopener noreferrer" do %>
    <%= image_tag("logo_EV.png", :alt => "logo écran village", :title => "aller sur le site d'Ecran Village", :class => "image-logo") %>
  <% end %>
  </div>
</div>
<br>

releases/20201219050137/app/views/layouts/_footer.html.erb
<div class="container">
      <center><h4>Plannings Cinéma 2020 par <a href="mailto:rodolphe.robles@sfr.fr", title="me contacter">Rodolphe Robles</a></h4>
      </center>
</div>

releases/20201219050137/app/views/layouts/_nav.html.erb
<nav class="navbar navbar-inverse navbar-static-top" role = "navigation">
<%= link_to 'Utilisateurs', users_path, :class => "btn btn-lg navbar-btn hidden-xs" %>
</nav>

releases/20201219050137/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EcranVillagePlannings</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width">
  </head>

  <body>
    <%= render "layouts/nav" %>
    <%= render "layouts/connexion" %>
      <p id="notice"><%= flash[:notice] %></p>
      <p id="error"><%= flash[:error] %></p>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

releases/20201219050137/app/views/users/_form.html.erb
<h1><span class="glyphicon glyphicon-warning-sign"></span> AVIS: </h1>
<p><strong>Aux curieux:</strong> Cette inscription ne sert qu'aux bénévoles d'Ecran Village, elle ne vous apportera rien d'autre. Si vous n'en faites pas partie, s'il vous plaît, revenez à l'accueil.</p>
<p><strong>Pour les bénévoles:</strong> Une fois inscrits, veuillez m'en avertir par mail pour que je vous autorise à accéder à l'édition des plannings.</p>
<br>
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

 <center>
     <div class="field">
       <%= f.label :prenom, :value => 'Prénom (court, sera utilisé lors des inscriptions pour les séances)' %><br>
       <%= f.text_field :prenom, :maxlength => 35, autofocus: true %>
     </div>
     <div class="field">
       <%= f.label :nom, :value => 'Nom de famille (facultatif)' %><br>
       <%= f.text_field :nom, :maxlength => 35 %>
     </div>
     <div class="field">
       <%= f.label :telephone, :value => 'Téléphone (facultatif)' %><br>
       <%= f.text_field :telephone, :maxlength => 35 %>
     </div>
     <div class="field">
       <%= f.label :email,'Adresse mail (indispensable: servira pour vous connecter)' %><br>
       <%= f.email_field :email, :maxlength => 40, autofocus: true %>
     </div>

     <p><strong>Important !</strong> si vous êtes en train de modifier votre utilisateur, vous devez retaper votre mot de passe et sa confirmation !</p>

    <div class="field">
       <%= f.label :password, :value => 'Mot de passe (minimum 5 caractères, à bien retenir, vous servira pour se connecter)' %><br />
       <%= f.password_field :password, :maxlength => 30, autofocus: true %>
    </div>
    <div class="field">
       <%= f.label :password_confirmation, :value => 'confirmation du mot de passe' %><br />
       <%= f.password_field :password_confirmation, autofocus: true %>
    </div>

    <div class="field">
     <%= f.label :role, :value => 'Permissions' %><br>
     <%= f.select :role, User::ROLES %>
    </div>

   <div class="actions">
     <input type="submit" class="btn btn-lg btn-warning" value="Valider" />
   </div>

<% end %>
 </center>

releases/20201219050137/app/views/users/edit.html.erb
<center>
<h1><strong>Modifier un utilisateur</strong></h1>
	<div class="container">
		<%= render 'form' %>
		<%= link_to 'Retour utilisateurs', users_path, :class => "btn btn-primary btn-lg" %>
	</div>
</center>
<br>

releases/20201219050137/app/views/users/index.html.erb
</center>
<div class="container">

  <center><h1><strong>Liste des utilisateurs</strong></h1></center>
  <br>
  <div class="container">
  <div class="actions hidden-xs">
 </div>
  <div class="row">
    <div class="col-md-12 table-croped">
      <table class="table table-responsive table-hover table-striped">
        <thead>
          <tr>
            <th>Prénom</th>
            <th>Nom</th>
            <th>Email</th>
            <th>Téléphone</th>
            <th>Modifier</th>
            <th>Role (permissions)</th>
            <th>Editer ou supprimer</th>
          </tr>
        </thead>
      <% @users.users_alphabet.each do |user| %>
        <tbody>
          <tr>
              <td><%= user.prenom.capitalize %></td>
              <td><%= user.nom.capitalize %></td>
              <td><%= user.email %></td>
              <td><%= user.telephone %></td>
              <td></td>
               <td class="info"><%= user.role %></td>
               <td class="danger"><span class="glyphicon glyphicon-trash"></span> <%= link_to 'Supprimer', user, method: :delete, data: { confirm: 'En êtes vous sûr ?'}, :class => "btn btn-danger" %> <br>
               <span class="glyphicon glyphicon-pencil"> </span> <%= link_to 'Editer', edit_user_path(user), data: { confirm: 'En êtes-vous sûr ?' }, :class => "btn btn-warning" %></td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>
<% end %>

releases/20201219050137/app/views/users/index.pdf.erb
<meta charset='utf-8' />
<% if can? :update, User %>
    <h2>Liste des Bénévoles (inscrits sur le plannings)</h2>
<table class="table table-responsive table-hover table-striped">
  <tbody>
    <tr>
      <th><strong>PRÉNOM</strong></th>
      <th><strong>NOM</strong></th>
      <th><strong>EMAIL</strong></th>
      <th><strong>TÉLÉPHONE</strong></th>
    </tr>
<% @users.users_alphabet.each do |user| %>
    <tr>
        <td><%= user.prenom.capitalize %></td>
        <td><%= user.nom.capitalize %></td>
         <td><%= user.email %></td>
         <td><%= user.telephone %></td>
    </tr>
  </tbody>
<% end %>
</table>
<% end %>

releases/20201219050137/app/views/users/new.html.erb
<center><h1>Inscription</h1></center>

<%= render 'form', user: @user %>

releases/20201219050137/app/views/users/show.html.erb
<center><p>
<h4><strong>Prénom:</strong> <%= @user.prenom %></h4>
  <h4><strong>Nom:</strong> <%= @user.nom %></h4>
  <h4><strong>Email:</strong> <%= @user.email %></h4>
  <h4><strong>Role:</strong> <%= @user.role %>
</p>


<%= link_to 'Modifier', edit_user_path(@user), :class => "btn btn-warning" %> |
<%= link_to 'Retour liste des utilisateurs', users_path, :class => "btn btn-primary" %>
</center>